#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)
#ifndef ANTIADDICTIONSERVICE_SWIFT_H
#define ANTIADDICTIONSERVICE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AntiAddictionService",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


/// AAKit 功能配置
SWIFT_CLASS("_TtC20AntiAddictionService26AntiAddictionConfiguration")
@interface AntiAddictionConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, AntiAddictionRealNameAuthState, open) {
  AntiAddictionRealNameAuthStateSuccess = 0,
  AntiAddictionRealNameAuthStateVerifying = 1,
  AntiAddictionRealNameAuthStateFail = 2,
};

@class NSString;
@class NSNumber;
@protocol AntiAddictionServiceCallback;

SWIFT_CLASS_NAMED("AntiAddictionService")
@interface AntiAddictionService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) AntiAddictionConfiguration * _Nonnull configuration;)
+ (AntiAddictionConfiguration * _Nonnull)configuration SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfiguration:(AntiAddictionConfiguration * _Nonnull)value;
+ (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)enableLogWithEnable:(BOOL)enable;
+ (void)setHost:(NSString * _Nonnull)host;
+ (void)setIdentifyHost:(NSString * _Nonnull)host;
/// 设置长连接地址，设置以后，进入游戏将会连接，退出登录会断开
/// \param address 长连接地址
///
+ (void)setWebsocketAddress:(NSString * _Nonnull)address;
+ (void)setAntiSecretKey:(NSString * _Nonnull)secretKey;
/// AAKit 配置方法
/// \param useSdkRealName 实名登记开关，默认值为 true
///
/// \param useSdkPaymentLimit 支付限制开关，默认值为 true
///
/// \param useSdkOnlineTimeLimit 在线时长限制开关，默认值为 true
///
+ (void)setFunctionConfig:(BOOL)useSdkPaymentLimit :(BOOL)useSdkOnlineTimeLimit;
/// 初始化 SDK
/// \param delegate 接收回调代理
///
/// \param gameIdentifier 游戏唯一标识符
///
+ (void)init:(id <AntiAddictionServiceCallback> _Nonnull)delegate gameIdentifier:(NSString * _Nullable)gameIdentifier SWIFT_METHOD_FAMILY(none);
/// 登录用户
/// \param userToken 用户唯一标识符，如用户 ID 等，不能为空
///
+ (void)login:(NSString * _Nonnull)userToken;
/// 进入游戏
+ (void)enterGame;
/// 离开游戏
+ (void)leaveGame;
/// 退出用户登录
+ (void)logout;
/// 获取用户类型
/// \param userId 用户 id
///
+ (NSInteger)getCurrentUserType SWIFT_WARN_UNUSED_RESULT;
/// 获取用户剩余时长
+ (NSInteger)getCurrentUserRemainTime SWIFT_WARN_UNUSED_RESULT;
/// 查询能否支付，直接返回支付限制相关回调类型 raw value，特殊情况使用
/// \param amount 支付金额，单位分
///
+ (NSInteger)checkCurrentPayLimit:(NSInteger)amount SWIFT_WARN_UNUSED_RESULT;
/// 查询能否支付
/// \param amount 支付金额，单位分
///
+ (void)checkPayLimit:(NSInteger)amount;
/// 设置已支付金额
/// \param amount 支付金额，单位分
///
+ (void)paySuccess:(NSInteger)amount;
/// 打开实名窗口，实名结果通过回调接受
+ (void)openRealName;
+ (BOOL)isHoliday SWIFT_WARN_UNUSED_RESULT;
/// 生成身份证兑换码（有效期从生成起6个小时整以内）
+ (NSString * _Nonnull)generateIDCode SWIFT_WARN_UNUSED_RESULT;
+ (void)startTimeStaticWithIsLogin:(BOOL)isLogin;
+ (void)stopTimeStatic;
/// 实名认证
/// \param userToken 用户唯一标识，如用户 ID
///
/// \param name 姓名
///
/// \param idCard 身份证
///
/// \param phone 手机号
///
/// \param completion 结果回调
///
+ (void)realNameAuthWithUserToken:(NSString * _Nonnull)userToken name:(NSString * _Nonnull)name idCard:(NSString * _Nonnull)idCard phone:(NSString * _Nonnull)phone completion:(void (^ _Nonnull)(enum AntiAddictionRealNameAuthState, NSString * _Nonnull))completion;
/// 检查实名状态
/// \param userToken 用户唯一标识，如用户 ID
///
/// \param completion 结果回调
///
+ (void)checkRealnameStateWithUserToken:(NSString * _Nonnull)userToken completion:(void (^ _Nonnull)(enum AntiAddictionRealNameAuthState, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))completion failureHandler:(void (^ _Nonnull)(NSString * _Nonnull))failureHandler;
+ (NSString * _Nullable)checkPlayTimeResultWithHandler:(void (^ _Nonnull)(NSString * _Nullable))handler SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP20AntiAddictionService28AntiAddictionServiceCallback_")
@protocol AntiAddictionServiceCallback <NSObject>
/// 回调
/// \param code 回调code
///
/// \param extra 回调信息
///
- (void)onCallbackWithCode:(NSInteger)code extra:(NSString * _Nullable)extra;
@end

typedef SWIFT_ENUM(NSInteger, AntiAddictionServiceResult, open) {
  AntiAddictionServiceResultLoginSuccess = 500,
  AntiAddictionServiceResultLogout = 1000,
  AntiAddictionServiceResultPlayTimeLimitNoTime = 1030,
  AntiAddictionServiceResultPayLimitNone = 1020,
  AntiAddictionServiceResultPayLimitReachLimit = 1025,
  AntiAddictionServiceResultSubmitPaySuccess = 1028,
  AntiAddictionServiceResultSubmitPayFail = 1029,
  AntiAddictionServiceResultOpenRealName = 1060,
  AntiAddictionServiceResultOpenAlertTip = 1095,
  AntiAddictionServiceResultCloseAlertTip = 1096,
  AntiAddictionServiceResultUpdateConfig = 1100,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.5 (swiftlang-1300.0.29.102 clang-1300.0.28.1)
#ifndef ANTIADDICTIONSERVICE_SWIFT_H
#define ANTIADDICTIONSERVICE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="AntiAddictionService",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


/// AAKit 功能配置
SWIFT_CLASS("_TtC20AntiAddictionService26AntiAddictionConfiguration")
@interface AntiAddictionConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, AntiAddictionRealNameAuthState, open) {
  AntiAddictionRealNameAuthStateSuccess = 0,
  AntiAddictionRealNameAuthStateVerifying = 1,
  AntiAddictionRealNameAuthStateFail = 2,
};

@class NSString;
@class NSNumber;
@protocol AntiAddictionServiceCallback;

SWIFT_CLASS_NAMED("AntiAddictionService")
@interface AntiAddictionService : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) AntiAddictionConfiguration * _Nonnull configuration;)
+ (AntiAddictionConfiguration * _Nonnull)configuration SWIFT_WARN_UNUSED_RESULT;
+ (void)setConfiguration:(AntiAddictionConfiguration * _Nonnull)value;
+ (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
+ (void)enableLogWithEnable:(BOOL)enable;
+ (void)setHost:(NSString * _Nonnull)host;
+ (void)setIdentifyHost:(NSString * _Nonnull)host;
/// 设置长连接地址，设置以后，进入游戏将会连接，退出登录会断开
/// \param address 长连接地址
///
+ (void)setWebsocketAddress:(NSString * _Nonnull)address;
+ (void)setAntiSecretKey:(NSString * _Nonnull)secretKey;
/// AAKit 配置方法
/// \param useSdkRealName 实名登记开关，默认值为 true
///
/// \param useSdkPaymentLimit 支付限制开关，默认值为 true
///
/// \param useSdkOnlineTimeLimit 在线时长限制开关，默认值为 true
///
+ (void)setFunctionConfig:(BOOL)useSdkPaymentLimit :(BOOL)useSdkOnlineTimeLimit;
/// 初始化 SDK
/// \param delegate 接收回调代理
///
/// \param gameIdentifier 游戏唯一标识符
///
+ (void)init:(id <AntiAddictionServiceCallback> _Nonnull)delegate gameIdentifier:(NSString * _Nullable)gameIdentifier SWIFT_METHOD_FAMILY(none);
/// 登录用户
/// \param userToken 用户唯一标识符，如用户 ID 等，不能为空
///
+ (void)login:(NSString * _Nonnull)userToken;
/// 进入游戏
+ (void)enterGame;
/// 离开游戏
+ (void)leaveGame;
/// 退出用户登录
+ (void)logout;
/// 获取用户类型
/// \param userId 用户 id
///
+ (NSInteger)getCurrentUserType SWIFT_WARN_UNUSED_RESULT;
/// 获取用户剩余时长
+ (NSInteger)getCurrentUserRemainTime SWIFT_WARN_UNUSED_RESULT;
/// 查询能否支付，直接返回支付限制相关回调类型 raw value，特殊情况使用
/// \param amount 支付金额，单位分
///
+ (NSInteger)checkCurrentPayLimit:(NSInteger)amount SWIFT_WARN_UNUSED_RESULT;
/// 查询能否支付
/// \param amount 支付金额，单位分
///
+ (void)checkPayLimit:(NSInteger)amount;
/// 设置已支付金额
/// \param amount 支付金额，单位分
///
+ (void)paySuccess:(NSInteger)amount;
/// 打开实名窗口，实名结果通过回调接受
+ (void)openRealName;
+ (BOOL)isHoliday SWIFT_WARN_UNUSED_RESULT;
/// 生成身份证兑换码（有效期从生成起6个小时整以内）
+ (NSString * _Nonnull)generateIDCode SWIFT_WARN_UNUSED_RESULT;
+ (void)startTimeStaticWithIsLogin:(BOOL)isLogin;
+ (void)stopTimeStatic;
/// 实名认证
/// \param userToken 用户唯一标识，如用户 ID
///
/// \param name 姓名
///
/// \param idCard 身份证
///
/// \param phone 手机号
///
/// \param completion 结果回调
///
+ (void)realNameAuthWithUserToken:(NSString * _Nonnull)userToken name:(NSString * _Nonnull)name idCard:(NSString * _Nonnull)idCard phone:(NSString * _Nonnull)phone completion:(void (^ _Nonnull)(enum AntiAddictionRealNameAuthState, NSString * _Nonnull))completion;
/// 检查实名状态
/// \param userToken 用户唯一标识，如用户 ID
///
/// \param completion 结果回调
///
+ (void)checkRealnameStateWithUserToken:(NSString * _Nonnull)userToken completion:(void (^ _Nonnull)(enum AntiAddictionRealNameAuthState, NSString * _Nonnull, NSString * _Nonnull, NSString * _Nonnull))completion failureHandler:(void (^ _Nonnull)(NSString * _Nonnull))failureHandler;
+ (NSString * _Nullable)checkPlayTimeResultWithHandler:(void (^ _Nonnull)(NSString * _Nullable))handler SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_PROTOCOL("_TtP20AntiAddictionService28AntiAddictionServiceCallback_")
@protocol AntiAddictionServiceCallback <NSObject>
/// 回调
/// \param code 回调code
///
/// \param extra 回调信息
///
- (void)onCallbackWithCode:(NSInteger)code extra:(NSString * _Nullable)extra;
@end

typedef SWIFT_ENUM(NSInteger, AntiAddictionServiceResult, open) {
  AntiAddictionServiceResultLoginSuccess = 500,
  AntiAddictionServiceResultLogout = 1000,
  AntiAddictionServiceResultPlayTimeLimitNoTime = 1030,
  AntiAddictionServiceResultPayLimitNone = 1020,
  AntiAddictionServiceResultPayLimitReachLimit = 1025,
  AntiAddictionServiceResultSubmitPaySuccess = 1028,
  AntiAddictionServiceResultSubmitPayFail = 1029,
  AntiAddictionServiceResultOpenRealName = 1060,
  AntiAddictionServiceResultOpenAlertTip = 1095,
  AntiAddictionServiceResultCloseAlertTip = 1096,
  AntiAddictionServiceResultUpdateConfig = 1100,
};

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
